services:
  backend:
    build:
      context: ./server

    container_name: inkrush-backend

    ports:
      - "8080:8080"

    restart: unless-stopped

  frontend:
    build:
      context: ./client

    container_name: inkrush-frontend

    ports:
      - "5173:5173"

    env_file:
      - ./client/.env

    depends_on:
      - backend

    restart: unless-stopped